### PR TITLE
Custom actions

### PR DESCRIPTION
**Pull request by luttje**
I'd like users to be able to bind (a sequence of) custom actions to different keyboard buttons.

Use cases:
- Bind keyboard `k` to gamepad press: `up, up, down down, left, right, left, right B, A`
- Bind keyboard `e` to gamepad joystick to rotate 360 degrees clockwise

Ideally I'd like to allow some form of scripting (javascript or Lua) for these custom actions, as well as more intuitive menu's for non-technical users.

### CODE REVIEW

**Comment by nxoet** [comment]
When will this feature be available?
I need this feature badly because without it, I have to use the keyboard back, plus a scripting software that I can send ultimate with one key. That software does not recognize the pad key.

**Comment by luttje** [comment]
@nxoet I can't make any promises, but I'll try my best to finish it before the end of the month.

_(This is just a hobby project though, so my work goes first if it needs to)_

**Comment by nxoet** [comment]
wow ,u r so nice, u reply to every message. r all u foreigners so kind? not like my country people, full of aso.
lua is good, the program i use now is based on lua too,it's called "按键精灵".
that's i used a script now:

Hwnd = Plugin.Window.Find("UnrealWindow", "Guilty Gear -Strive-  ")
Do
    Delay 20
    Hwnd2 = Plugin.Window.Foreground()
    If Hwnd = Hwnd2 Then 
        K = WaitKey
        '大招 The Ultimate
        If K = 70  Then 
            KeyDown "D", 1
            Delay 20
            KeyDown "S", 1
            Delay 20
            KeyUp "D", 1
            Delay 20
            KeyDown "A", 1
            Delay 20
            KeyUp "S", 1
            Delay 20
            KeyUp "A", 1
            Delay 20
            KeyDown "D", 1
            Delay 20
            KeyDown "Num 6", 1
            KeyDown "Num 0", 1
            Delay 20
            KeyUp "D", 1
            Delay 20
            KeyUp "Num 6", 1
            KeyUp "Num 0", 1
            '角色在右大招 The Ultimate when Character on right side
        ElseIf K = 16 Then
            KeyDown "A", 1
            Delay 20
            KeyDown "S", 1
            Delay 20
            KeyUp "A", 1
            Delay 20
            KeyDown "D", 1
            Delay 20
            KeyUp "S", 1
            Delay 20
            KeyUp "D", 1
            Delay 20
            KeyDown "A", 1
            Delay 20
            KeyDown "Num 6", 1
            KeyDown "Num 0", 1
            Delay 20
            KeyUp "A", 1
            Delay 20
            KeyUp "Num 6", 1
            KeyUp "Num 0", 1
        End If
    End If
Loop

i think u can just add a inputbox under the bind let us write the script.
thank u again.

**Comment by luttje** [comment]
Thanks for the compliment! To answer your question: there's people of varying kindness here on the other side of the planet as well, sometimes rude, but mostly nice ;)

Back on topic: I'll probably finish a version without scripting first. In the upcoming version you will use menu's to configure the tool. I will add scripting with Lua and/or javascript in the future.

I'll see if I can add all the features to make your script possible.

**Pull request merged**
